
" Setup XDG compliance
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

set encoding=utf-8
set t_Co=256
syntax on

" Show whitespace
set listchars=eol:$,tab:>-,trail:~,extends:›,precedes:‹,nbsp:·
set list

set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set expandtab

set number relativenumber
set nu rnu
