
[[language]]
name = "python"
language-servers = [
    "basedpyright",
    "ruff",
    { name = "jedi", except-features = ["document-symbols", "workspace-symbols"] },
    { name = "pylsp", except-features = ["document-symbols", "workspace-symbols"] }
]
